// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVzGjIzicx-x3TKMGNN5mNXpE5wMFlhV4',
    appId: '1:999980102152:web:163c615a2c18c59c4997bd',
    messagingSenderId: '999980102152',
    projectId: 'moviemania-9204c',
    authDomain: 'moviemania-9204c.firebaseapp.com',
    storageBucket: 'moviemania-9204c.appspot.com',
    measurementId: 'G-KSR9CKE6EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-hjUwLJZp0py2ik0-YrZzliBE5UKIQ0',
    appId: '1:999980102152:android:e1851ff1144f113b4997bd',
    messagingSenderId: '999980102152',
    projectId: 'moviemania-9204c',
    storageBucket: 'moviemania-9204c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAr6Qjvtk3_NuhJUVY9h38BKgmjwKVw5U',
    appId: '1:999980102152:ios:b7fce371afe8203c4997bd',
    messagingSenderId: '999980102152',
    projectId: 'moviemania-9204c',
    storageBucket: 'moviemania-9204c.appspot.com',
    iosClientId: '999980102152-3j59tubngmng3ol1sdapgpl3cg4u2f8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.r08fullmovieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAr6Qjvtk3_NuhJUVY9h38BKgmjwKVw5U',
    appId: '1:999980102152:ios:b7fce371afe8203c4997bd',
    messagingSenderId: '999980102152',
    projectId: 'moviemania-9204c',
    storageBucket: 'moviemania-9204c.appspot.com',
    iosClientId: '999980102152-3j59tubngmng3ol1sdapgpl3cg4u2f8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.r08fullmovieapp',
  );
}
